### ISSUE TITLE
How to get gene symbols

### ISSUE THREAD

**Issue by crj32** [ruolin/strawberry#30]
Hi

I have run strawberry on our data in the genome guided mode, is there an easy way you know if of getting the gene symbols of these new transcripts? Further, is there a way to add the gene symbols to the .gtf annotation file?

I know I could write either a blast script to do this or use the chromosome coordinates, but thought I'd ask anyways because you may know.

In stringtie they are allocated their original gene symbol in the .gtf automatically which helps with downstream analysis I do.

Thanks,

Chris

**Comment by ruolin** [comment]
@crj32 Thank you for your suggestions. I have made a new release. If you use -g option and providing a reference annotation file, Strawberry will utilize that annotation and if the de-novo assembled transcripts match the reference gene coordinates, these transcripts will have that gene symbols. Otherwise, new ids will be given. Are you working on the model organisms? Please update your Strawberry to version 1.0.5, which is the current master.

**Comment by ruolin** [comment]
@ruolin I saw on the closed issue that you have a problem with the new version?

**Comment by crj32** [comment]
Yes I closed that because I changed the command and it worked OK.
